<script setup>
import { onMounted, ref, defineProps } from 'vue'
// import { fetchApiCall, handleError } from '../../utils/api'
import * as d3 from 'd3'
  
// these props will be random numbers generated by the Image Viewer component until we can actually get data
const props = defineProps({
  xaxis: {
    type: Number,
    required: true
  },
  yaxis: {
    type: Number,
    required: true
  }
})
const svg = ref(null)


const displayData = (data) => {
  if(data) {
    console.log(data)
  }
}

//bogus api call to get the data
// this should be triggered by the Image Viewer component after a line is drawn
async function getPlotValues() {
  // const url = '/api/plot_values'
  // const requestBody = {
  // props from Image Viewer from the response of the api call with coordinates
  // }
  // await fetchApiCall({url: url, method: 'GET', body: requestBody,  successCallback: displayData, failCallback: handleError})
  if (props.xaxis && props.yaxis) {
    displayData({x: props.xaxis, y: props.yaxis})
  }
}
  
onMounted(() => {
  if (props.xaxis && props.yaxis) {
    getPlotValues()
  }

  const margin = { top: 20, right: 20, bottom: 30, left: 50 },
    width = 600 - margin.left - margin.right,
    height = 400 - margin.top - margin.bottom
  
  // The two domains can be dynamically changed to fit the data
  const x = d3.scaleLinear()
    .domain([0, 500])
    .range([0, width])
  
  const y = d3.scaleLinear()
    .domain([0, 500])
    .range([height, 0])
  
  const svgElement = d3.select(svg.value)
    .append('g')
    .attr('transform', `translate(${margin.left},${margin.top})`)
  
  // Add X axis
  svgElement.append('g')
    .attr('class', 'x axis')
    .attr('transform', `translate(0,${height})`)
    .call(d3.axisBottom(x))
  
  // Add Y axis
  svgElement.append('g')
    .attr('class', 'y axis')
    .call(d3.axisLeft(y))
})
</script>
  
<template>
  <div>
    <svg
      ref="svg"
      width="600"
      height="400"
    />
  </div>
</template>
